[pytest]
addopts = --import-mode=importlib
pythonpath =
    .
    test

testpaths =
    test/cases/core
    test/cases/quant
    test/cases/app
    test/cases/processor
    test/cases/format
